root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - import
  - jest
extends:
  - eslint:recommended
  - next
  - next/core-web-vitals
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:jest/recommended
  - prettier
settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
rules:
  sort-imports: 0
  import/order: [2, { "alphabetize": { "order": "asc" } }]
